name: flutter_slicing_ui_instagram
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.5.0
  carousel_slider: ^4.2.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - image/pp.jpeg
    - image/ig.png
    - image/plane.png
    - image/comment.png
    - image/add.png
    - image/reels.png
    - image/redHeart.png
    - image/lambo1.jpg
    - image/lambo2.png
    - image/astro.jpg
    - image/apo.jpg
    - image/spider.jpg
    - image/sword.png

  fonts:
    - family: Billabong
      fonts:
        - asset: fonts/Billabong.ttf
